### ISSUE TITLE
loads infinitely

### ISSUE THREAD

**Issue by quantenzitrone** [Lioncat6/SAMBL#1]
when i enter an artist url and click on search, SAMBL just loads infinitely

**Comment by Lioncat6** [comment]
At the moment, the site is supposed to automatically redirect you to this Google form: https://docs.google.com/forms/d/178zCbmaoWACBlM_JH9snkiuQFZ0eeZ6lNAACwBQpvJg/edit?usp=drivesdk&chromeless=1

Which is necessary in order to login with spotify at the moment due to a pending application request. Evidently, it did not redirect you, probably due to a popup blocker.

**Comment by quantenzitrone** [comment]
ok i couldn't get the site to redirect me, but i filled out the form

it may be good to leave this open until the application request is finished, so people with the same problem find this easily

**Comment by Lioncat6** [comment]
Alright,  you should have access
 now![Screenshot_20240819_110033_Chrome.png](https://github.com/user-attachments/assets/6d231e82-7b97-41fe-8d0a-7d482c9f45ef)


Spotify is really taking their time...

**Comment by Lioncat6** [comment]
Update: SAMBL now has a server and therefor no longer requires a user long, this issue should no longer occur.
