### ISSUE TITLE
Missing content.

### ISSUE THREAD

**Issue by LeoDasModell** [Lioncat6/SAMBL#6]
Some content is missing, like from Blink-182.

**Comment by Lioncat6** [comment]
How so? Can you provide some more context? Do note, the data SAMBL displays is only what the Spotify API returns and as such will only contain the content publically available in the region my server is hosted in. The particular server host I'm using happens to be hosted in Chicago, Illinois, and as such will only show content available in the United States.

**Comment by LeoDasModell** [comment]
Hi, here's an example: https://open.spotify.com/intl-es/album/3bL8GdAgDbtbd6U9iIjS7T.

The album ALL IN MY HEAD / NO FUN does not appear on SAMBL.

There is also another type of error, for example with Chris Cornell.

On the Carry On album (https://open.spotify.com/album/7DTYi2YCfQZGDyeedTdNGb) it says it has 14 songs, but on https://musicbrainz.org/release/f07a5a18-2cb9-3d9b-8c28-d75f49876be3 it says it has 15 songs.

**Comment by Lioncat6** [comment]
All in my head /No fun has been replaced with https://open.spotify.com/album/3wU2wXacpwqetSRloR0nMX?si=TYJBAbF9Tge0TfhtCTw3Rw by the artist. It is impossible to "delete" an album from spotify, the songs inside of it just become unplayable, the reason why the songs in that album remain playable is because they exist in another, still listed album. Because of this, the spotify api doesn't return this information from the artist page, and sambl can't display it. 

The MB release for this album:  https://open.spotify.com/album/7DTYi2YCfQZGDyeedTdNGb is https://musicbrainz.org/release/3f4f35db-cdef-4ca2-9ce7-31eb70d847a3 not https://musicbrainz.org/release/f07a5a18-2cb9-3d9b-8c28-d75f49876be3 . If you use the harmony button, it should match the correct musicbrainz release (as long as the person who added it entered a upc). Sambl just grabs the first available album that matches the same name should it not be able to find one with a matching link, leading to this. I could partially mitigate this  by making sure it only matches albums of the same length, but I can't check spotify upcs without making individual api calls for each track, which would be impractical.

**Comment by Lioncat6** [comment]
Closing this issue soon...

**Comment by Lioncat6** [comment]
Refuses to elaborate
